- name: Deploy Docker containers
  hosts: all
  become: yes
  roles:
    - role: db
      when: "'db' in group_names"
    - role: api
      when: "'api' in group_names"
    - role: web
      when: "'web' in group_names"
